load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "rebaze-cmake",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:chumsky",
        "@crates//:ariadne",
        "@crates//:anyhow",
        "@crates//:thiserror",
        "@crates//:serde",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "rebaze-cmake_test",
    crate = ":rebaze-cmake",
    edition = "2024",
)

rust_binary(
    name = "cmake_corpus",
    srcs = ["src/bin/corpus.rs"],
    edition = "2024",
    deps = [
        ":rebaze-cmake",
        "@crates//:anyhow",
    ],
)
