[package]
name = "rebaze-cmake"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CMake file parser for rebaze"

[lints]
workspace = true

[dependencies]
chumsky.workspace = true
ariadne.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
