load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "rebaze-core",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/rebaze-bazel",
        "//crates/rebaze-cmake",
        "//crates/rebaze-cmake-file-api",
        "//crates/rebaze-gradle",
        "@crates//:anyhow",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:thiserror",
        "@crates//:toml",
        "@crates//:tracing",
        "@crates//:walkdir",
    ],
)
