[package]
name = "rebaze-gradle"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Gradle build file parser for rebaze"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
walkdir.workspace = true
tracing.workspace = true
globset.workspace = true
