//! Bazel file generation logic.

use std::fmt::Write;

/// Represents a generated Bazel file.
pub struct BazelFile {
    pub path: String,
    pub content: String,
}

#[must_use]
pub fn generate_module_bazel(project: &rebaze_gradle::GradleProject) -> String {
    let mut content = String::new();
    let module_name = project.name.replace('-', "_");

    let _ = write!(
        content,
        r#""""Bazel module for {name} - generated by rebaze."""

module(
    name = "{module_name}",
    version = "0.1.0",
)

"#,
        name = project.name
    );

    // Detect language from plugins
    let has_kotlin = project.plugins.iter().any(|p| p.id.contains("kotlin"));
    let has_java = project.plugins.iter().any(|p| p.id.contains("java"));

    if has_kotlin {
        content.push_str(
            r#"# Kotlin support
bazel_dep(name = "rules_kotlin", version = "2.1.0")
bazel_dep(name = "rules_java", version = "8.6.4")

"#,
        );
    } else if has_java {
        content.push_str(
            r#"# Java support
bazel_dep(name = "rules_java", version = "8.6.4")
bazel_dep(name = "rules_jvm_external", version = "6.6")

"#,
        );
    }

    // Add Maven dependencies if present
    if !project.dependencies.is_empty() {
        content.push_str(
            r#"# Maven dependencies
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
"#,
        );

        for dep in &project.dependencies {
            if !dep.version.is_empty() {
                let _ = writeln!(
                    content,
                    "        \"{}:{}:{}\",",
                    dep.group, dep.artifact, dep.version
                );
            }
        }

        content.push_str(
            r#"    ],
)
use_repo(maven, "maven")
"#,
        );
    }

    content
}

#[must_use]
pub fn generate_root_build(project: &rebaze_gradle::GradleProject) -> String {
    let mut content = String::new();
    let name = &project.name;

    let _ = writeln!(
        content,
        "# Root BUILD file for {name} - generated by rebaze\n"
    );

    // Add exports_files for common files
    content.push_str(
        r#"exports_files([
    "MODULE.bazel",
])
"#,
    );

    content
}

#[must_use]
pub fn generate_subproject_build(
    _project: &rebaze_gradle::GradleProject,
    subproject: &str,
) -> String {
    let target_name = subproject
        .split(':')
        .next_back()
        .unwrap_or(subproject)
        .replace('-', "_");

    format!(
        r#"# BUILD file for {subproject} - generated by rebaze

load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "{target_name}",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        # TODO: Add dependencies
    ],
)

java_test(
    name = "{target_name}_test",
    srcs = glob(["src/test/java/**/*.java"]),
    test_class = "TODO",
    deps = [
        ":{target_name}",
        # TODO: Add test dependencies
    ],
)
"#
    )
}
