//! Bazel file generator for rebaze.

use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;

// Re-export for use by other crates
pub use crate::config::MigrationConfig;
pub use crate::generator::BazelFile;
pub use crate::third_party::{deduplicate_modules, DepsStrategy, ThirdPartyConfig};

pub mod config;
pub mod filters;
mod cmake_generator;
mod generator;
pub use rebaze_starlark as starlark;
pub mod third_party;

/// Generate Bazel files from a parsed Gradle project.
#[must_use]
pub fn generate(project: &rebaze_gradle::GradleProject) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Generate MODULE.bazel
    let module_bazel = generator::generate_module_bazel(project);
    files.insert("MODULE.bazel".to_string(), module_bazel);

    // Generate root BUILD.bazel
    let root_build = generator::generate_root_build(project);
    files.insert("BUILD.bazel".to_string(), root_build);

    // Generate BUILD.bazel for each subproject
    for subproject in &project.subprojects {
        let subproject_path = subproject.replace(':', "/");
        let build_path = format!("{subproject_path}/BUILD.bazel");
        let build_content = generator::generate_subproject_build(project, subproject);
        files.insert(build_path, build_content);
    }

    // Generate .bazelversion
    files.insert(".bazelversion".to_string(), "9.0.0\n".to_string());

    tracing::info!("Generated {} Bazel files", files.len());

    files
}

/// Generate Bazel files from a parsed CMake project.
#[must_use]
pub fn generate_from_cmake(project: &rebaze_cmake::CMakeProject) -> HashMap<String, String> {
    generate_from_cmake_with_config(project, &MigrationConfig::default())
}

/// Generate Bazel files from a parsed CMake project with custom configuration.
#[must_use]
pub fn generate_from_cmake_with_config(
    project: &rebaze_cmake::CMakeProject,
    config: &MigrationConfig,
) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Generate MODULE.bazel
    let module_bazel = cmake_generator::generate_module_bazel(project, config);
    files.insert("MODULE.bazel".to_string(), module_bazel);

    // Generate root BUILD.bazel
    let root_build = cmake_generator::generate_root_build(project);
    files.insert("BUILD.bazel".to_string(), root_build);

    // Generate .bazelversion
    files.insert(".bazelversion".to_string(), "9.0.0\n".to_string());

    // Generate .bazelrc with C/C++ settings (no system includes - handled by module extension)
    let bazelrc = generate_cpp_bazelrc(project, &[]);
    files.insert(".bazelrc".to_string(), bazelrc);

    // Generate third_party/ directory for pkg-config dependencies
    if !project.pkg_config_modules.is_empty() {
        let config = ThirdPartyConfig::default();

        // Deduplicate modules once upfront for all generation functions
        let modules = deduplicate_modules(&project.pkg_config_modules);

        // Generate extensible BUILD.bazel with aliases and system library fallbacks
        let mut third_party_build = third_party::generate_build_file(&modules, &config);

        // Append source build targets (used when strategy = "source")
        third_party_build.push_str("\n\n");
        third_party_build.push_str(&third_party::generate_source_build_targets(&modules));
        files.insert("third_party/BUILD.bazel".to_string(), third_party_build);

        // Generate config.bzl for customization
        let config_bzl = third_party::generate_config_bzl(&modules, &config);
        files.insert("third_party/config.bzl".to_string(), config_bzl);

        // Generate source.bzl for building from source (includes module extension)
        let source_bzl = third_party::generate_source_bzl(&modules);
        files.insert("third_party/source.bzl".to_string(), source_bzl);

        // Generate system_deps.bzl module extension for system libraries
        let system_deps_bzl = third_party::generate_system_deps_bzl(&modules);
        files.insert("third_party/system_deps.bzl".to_string(), system_deps_bzl);
    }

    tracing::info!("Generated {} Bazel files for CMake project", files.len());

    files
}

/// Supported C++ standards
const SUPPORTED_CXX_STANDARDS: &[&str] = &["98", "03", "11", "14", "17"];
/// Experimental C++ standards (work but may have issues)
const EXPERIMENTAL_CXX_STANDARDS: &[&str] = &["20", "23", "26"];

/// Generate a .bazelrc suitable for C/C++ projects.
#[allow(clippy::option_if_let_else)]
fn generate_cpp_bazelrc(project: &rebaze_cmake::CMakeProject, system_includes: &[String]) -> String {
    let mut lines = vec![
        "# Generated by rebaze - C/C++ project settings".to_string(),
        "# NOTE: Review and adjust these settings for your project".to_string(),
        String::new(),
    ];

    // Add system include paths detected from pkg-config
    if !system_includes.is_empty() {
        lines.push("# System include paths (detected from pkg-config during migration)".to_string());
        lines.push("# NOTE: These paths are machine-specific - adjust for your system".to_string());
        lines.push("# WARNING: Using system libraries makes builds non-hermetic".to_string());
        for path in system_includes {
            lines.push(format!("common --copt=-isystem{path}"));
        }
        lines.push(String::new());

        // Collect unique root directories for sandbox access
        let mut sandbox_paths: Vec<String> = Vec::new();
        for path in system_includes {
            // Find the Homebrew/system root (e.g., /opt/homebrew, /usr/local, /usr)
            if let Some(root) = find_sandbox_root(path) {
                if !sandbox_paths.contains(&root) {
                    sandbox_paths.push(root);
                }
            }
        }

        if !sandbox_paths.is_empty() {
            lines.push("# Sandbox configuration for system library access".to_string());
            lines.push("# This allows Bazel's sandbox to access system include paths".to_string());
            for path in &sandbox_paths {
                lines.push(format!("build --sandbox_add_mount_pair={path}"));
            }
            lines.push(String::new());
        }
    }

    // Detect C vs C++ from project languages
    let has_cxx = project.languages.iter().any(|l| l == "CXX" || l == "C++");
    let has_c = project.languages.iter().any(|l| l == "C");

    // C++ standard settings
    if has_cxx {
        let (cxx_std, note) = match &project.cxx_standard {
            Some(std) => {
                if SUPPORTED_CXX_STANDARDS.contains(&std.as_str()) {
                    (std.clone(), None)
                } else if EXPERIMENTAL_CXX_STANDARDS.contains(&std.as_str()) {
                    tracing::warn!(
                        "C++{std} detected - this is experimental and may have toolchain compatibility issues"
                    );
                    (std.clone(), Some(format!("# WARNING: C++{std} is experimental - verify toolchain support")))
                } else {
                    tracing::warn!("Unknown C++ standard '{std}' detected, defaulting to C++17");
                    ("17".to_string(), Some(format!("# WARNING: Unknown standard '{std}' was detected, using C++17")))
                }
            }
            None => ("17".to_string(), None), // Default to C++17
        };

        if let Some(note) = note {
            lines.push(note);
        }
        lines.push(format!("# C++ standard (detected: {})", project.cxx_standard.as_deref().unwrap_or("not specified")));
        lines.push(format!("common --cxxopt=-std=c++{cxx_std}"));
        lines.push(format!("common --host_cxxopt=-std=c++{cxx_std}"));
        lines.push(String::new());
    }

    // C standard settings
    if has_c && !has_cxx {
        let c_std = match &project.c_standard {
            Some(std) => {
                // Normalize common variants
                match std.as_str() {
                    "90" | "89" => "90",
                    "99" => "99",
                    "11" => "11",
                    "17" | "18" => "17",
                    "23" => "23",
                    _ => {
                        tracing::warn!("Unknown C standard '{std}' detected, defaulting to C11");
                        "11"
                    }
                }
            }
            None => "11", // Default to C11
        };

        lines.push(format!("# C standard (detected: {})", project.c_standard.as_deref().unwrap_or("not specified")));
        lines.push(format!("common --copt=-std=c{c_std}"));
        lines.push(format!("common --host_copt=-std=c{c_std}"));
        lines.push(String::new());
    }

    // Common settings (apply to all commands: build, test, run, query, etc.)
    lines.extend([
        "# Allow empty glob patterns - rebaze generates .h and .hpp patterns".to_string(),
        "# NOTE: Review glob patterns in BUILD.bazel and remove allow_empty if not needed".to_string(),
        "common --incompatible_disallow_empty_glob=false".to_string(),
        String::new(),
        "# Enable position-independent code (required for shared libraries)".to_string(),
        "common --copt=-fPIC".to_string(),
        String::new(),
        "# Warning settings (adjust based on your project's warning policy)".to_string(),
        "common --copt=-Wall".to_string(),
        "common --copt=-Wextra".to_string(),
        String::new(),
        "# Test settings".to_string(),
        "test --test_output=errors".to_string(),
        String::new(),
        "# CI config".to_string(),
        "common:ci --color=yes".to_string(),
        "common:ci --curses=no".to_string(),
        String::new(),
    ]);

    lines.join("\n")
}

/// Find the root directory to mount in sandbox for a system path.
/// E.g., /opt/homebrew/Cellar/glib/2.86.3/include -> /opt/homebrew
fn find_sandbox_root(path: &str) -> Option<String> {
    let path = std::path::Path::new(path);

    // Common system roots to check
    let known_roots = [
        "/opt/homebrew",
        "/usr/local",
        "/Library/Developer/CommandLineTools",
        "/Applications/Xcode.app",
    ];

    for root in &known_roots {
        if path.starts_with(root) {
            return Some((*root).to_string());
        }
    }

    // For /usr paths, just use /usr
    if path.starts_with("/usr") {
        return Some("/usr".to_string());
    }

    // For other paths, use the first two components
    let mut components = path.components();
    if let (Some(c1), Some(c2)) = (components.next(), components.next()) {
        let root = std::path::PathBuf::from(c1.as_os_str()).join(c2.as_os_str());
        return Some(root.to_string_lossy().to_string());
    }

    None
}

/// Write generated Bazel files to disk.
pub fn write_files<S: std::hash::BuildHasher>(
    root: &Path,
    files: &HashMap<String, String, S>,
) -> Result<()> {
    for (path, content) in files {
        let full_path = root.join(path);

        if let Some(parent) = full_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(&full_path, content)?;
        tracing::info!("Wrote {}", full_path.display());
    }

    Ok(())
}
