//! Bazel file generator for rebaze.

use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;

// Re-export for use by other crates
pub use crate::generator::BazelFile;

mod cmake_generator;
mod generator;

/// Generate Bazel files from a parsed Gradle project.
#[must_use]
pub fn generate(project: &rebaze_gradle::GradleProject) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Generate MODULE.bazel
    let module_bazel = generator::generate_module_bazel(project);
    files.insert("MODULE.bazel".to_string(), module_bazel);

    // Generate root BUILD.bazel
    let root_build = generator::generate_root_build(project);
    files.insert("BUILD.bazel".to_string(), root_build);

    // Generate BUILD.bazel for each subproject
    for subproject in &project.subprojects {
        let subproject_path = subproject.replace(':', "/");
        let build_path = format!("{subproject_path}/BUILD.bazel");
        let build_content = generator::generate_subproject_build(project, subproject);
        files.insert(build_path, build_content);
    }

    // Generate .bazelversion
    files.insert(".bazelversion".to_string(), "9.0.0\n".to_string());

    tracing::info!("Generated {} Bazel files", files.len());

    files
}

/// Generate Bazel files from a parsed CMake project.
#[must_use]
pub fn generate_from_cmake(project: &rebaze_cmake::CMakeProject) -> HashMap<String, String> {
    let mut files = HashMap::new();

    // Generate MODULE.bazel
    let module_bazel = cmake_generator::generate_module_bazel(project);
    files.insert("MODULE.bazel".to_string(), module_bazel);

    // Generate root BUILD.bazel
    let root_build = cmake_generator::generate_root_build(project);
    files.insert("BUILD.bazel".to_string(), root_build);

    // Generate .bazelversion
    files.insert(".bazelversion".to_string(), "9.0.0\n".to_string());

    // Generate .bazelrc with C++ settings
    let bazelrc = generate_cpp_bazelrc();
    files.insert(".bazelrc".to_string(), bazelrc);

    tracing::info!("Generated {} Bazel files for CMake project", files.len());

    files
}

/// Generate a .bazelrc suitable for C++ projects.
fn generate_cpp_bazelrc() -> String {
    r"# Generated by rebaze - C++ project settings

# Use C++17 by default
build --cxxopt=-std=c++17
build --host_cxxopt=-std=c++17

# Enable position-independent code
build --copt=-fPIC

# Warning settings
build --copt=-Wall
build --copt=-Wextra

# Test settings
test --test_output=errors

# CI config
build:ci --color=yes
build:ci --curses=no
"
    .to_string()
}

/// Write generated Bazel files to disk.
pub fn write_files<S: std::hash::BuildHasher>(
    root: &Path,
    files: &HashMap<String, String, S>,
) -> Result<()> {
    for (path, content) in files {
        let full_path = root.join(path);

        if let Some(parent) = full_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(&full_path, content)?;
        tracing::info!("Wrote {}", full_path.display());
    }

    Ok(())
}
