//! Third-party dependency configuration and generation.
//!
//! This module generates extensible BUILD files for third-party dependencies,
//! supporting multiple resolution strategies:
//!
//! - `system`: Use system-installed libraries via new_local_repository (non-hermetic)
//! - `source`: Build from source using rules_foreign_cc (hermetic)
//! - `conan`: Use Conan package manager
//! - `vcpkg`: Use vcpkg package manager
//! - `prebuilt`: Use pre-built libraries from filesystem
//! - `bazelle`: Use bazelle/gazelle_cc to generate BUILD files
//! - `custom`: User-defined resolution

use rebaze_cmake::PkgConfigModule;

/// Dependency resolution strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DepsStrategy {
    /// Use system libraries via new_local_repository (non-hermetic, but works)
    /// This is the default since it works out of the box when deps are installed.
    #[default]
    System,
    /// Build from source using rules_foreign_cc (hermetic, recommended for production)
    Source,
    /// Use Conan package manager
    Conan,
    /// Use vcpkg package manager
    Vcpkg,
    /// Use pre-built libraries from filesystem
    Prebuilt,
    /// Use bazelle/gazelle_cc to generate BUILD files for deps
    Bazelle,
    /// User provides custom resolution
    Custom,
}

/// Configuration for third-party dependency generation.
#[derive(Debug, Clone, Default)]
pub struct ThirdPartyConfig {
    /// Default strategy for resolving dependencies
    pub default_strategy: DepsStrategy,
    /// Path to prebuilt libraries (for Prebuilt strategy)
    pub prebuilt_path: Option<String>,
    /// Conan profile to use
    pub conan_profile: Option<String>,
    /// vcpkg triplet to use
    pub vcpkg_triplet: Option<String>,
}

/// Generate the third_party/BUILD.bazel file.
pub fn generate_build_file(
    pkg_config_modules: &[PkgConfigModule],
    _config: &ThirdPartyConfig,
) -> String {
    // Check if any pkg-config packages are available on this system
    let any_pkg_config_available = pkg_config_modules
        .iter()
        .any(|pkg| probe_pkg_config(&pkg.packages).is_some());

    let pkg_config_note = if any_pkg_config_available {
        "# NOTE: System library flags were detected via pkg-config during migration.\n#       These paths are system-specific and may need adjustment on other machines."
    } else {
        "# NOTE: pkg-config was not available during migration.\n#       You need to add copts for include paths. Run: pkg-config --cflags <package>"
    };

    let mut lines = vec![
        format!(
            r#"# Third-party dependencies - Generated by rebaze
#
# This file provides extensible dependency resolution. Edit third_party/config.bzl
# to configure how dependencies are resolved.
#
# Supported strategies:
#   - system:   Use system libraries via pkg-config (non-hermetic)
#   - source:   Build from source with rules_foreign_cc (hermetic, recommended)
#   - conan:    Use Conan package manager
#   - vcpkg:    Use vcpkg package manager
#   - prebuilt: Use pre-compiled libraries from filesystem
#   - custom:   Implement your own resolution in config.bzl
#
{pkg_config_note}

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//third_party:config.bzl", "DEPS_CONFIG", "resolve_dep")

package(default_visibility = ["//visibility:public"])"#
        ),
        String::new(),
    ];

    // Generate an alias for each dependency that uses the configured resolver
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages_str = pkg.packages.join(", ");

        lines.push(format!("# {} -> {}", pkg.prefix, packages_str));
        lines.push(format!(
            r#"alias(
    name = "{target_name}",
    actual = resolve_dep("{target_name}"),
)"#
        ));
        lines.push(String::new());
    }

    // Generate fallback cc_library rules for system strategy
    lines.push("# ============================================================".to_string());
    lines.push("# System library fallbacks (used when strategy = \"system\")".to_string());
    lines.push("# ============================================================".to_string());
    lines.push(String::new());

    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages_str = pkg.packages.join(", ");

        // Try to detect actual flags from pkg-config
        let detected_flags = probe_pkg_config(&pkg.packages);

        lines.push("cc_library(".to_string());
        lines.push(format!("    name = \"{target_name}_system\","));

        // NOTE: We only include linkopts here, NOT copts with include paths.
        // Include paths must go in .bazelrc as --copt=-isystem/path because
        // rules_cc validates include paths in copts and rejects absolute system paths.

        if let Some(ref flags) = detected_flags {
            // Extract only linker flags (not -I or other compiler flags)
            let linkopts: Vec<_> = flags.libs.iter()
                .filter(|f| f.starts_with("-l") || f.starts_with("-L"))
                .collect();

            if !linkopts.is_empty() {
                lines.push("    linkopts = [".to_string());
                for opt in &linkopts {
                    lines.push(format!("        \"{opt}\","));
                }
                lines.push("    ],".to_string());
            }
        } else {
            // Fallback to guessed linkopts when pkg-config not available
            let linkopts = generate_system_linkopts(&pkg.packages);
            if !linkopts.is_empty() {
                lines.push("    linkopts = [".to_string());
                for opt in &linkopts {
                    lines.push(format!("        \"{opt}\","));
                }
                lines.push("    ],".to_string());
            }
            lines.push(format!(
                "    # TODO: pkg-config not available. Add linkopts from:"
            ));
            lines.push(format!(
                "    # pkg-config --libs {packages_str}"
            ));
        }

        lines.push(")".to_string());
        lines.push(String::new());
    }

    lines.join("\n")
}

/// Generate the third_party/config.bzl file.
pub fn generate_config_bzl(
    pkg_config_modules: &[PkgConfigModule],
    config: &ThirdPartyConfig,
) -> String {
    let default_strategy = match config.default_strategy {
        DepsStrategy::System => "system",
        DepsStrategy::Source => "source",
        DepsStrategy::Conan => "conan",
        DepsStrategy::Vcpkg => "vcpkg",
        DepsStrategy::Prebuilt => "prebuilt",
        DepsStrategy::Bazelle => "bazelle",
        DepsStrategy::Custom => "custom",
    };

    let mut lines = vec![
        format!(
            r#""""Configuration for third-party dependencies.

Edit this file to customize how dependencies are resolved.
"""

# Default resolution strategy for all dependencies.
# Options: "system", "source", "conan", "vcpkg", "prebuilt", "custom"
DEFAULT_STRATEGY = "{default_strategy}"

# Per-dependency configuration.
# Override the strategy or provide additional config for specific deps.
DEPS_CONFIG = {{"#
        ),
    ];

    // Generate config entries for each dependency
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages: Vec<_> = pkg
            .packages
            .iter()
            .map(|p| format!("\"{}\"", p))
            .collect();

        lines.push(format!(
            r#"    "{target_name}": {{
        "pkg_config": [{packages}],
        # "strategy": "system",  # Override default strategy
        # "conan_package": "glib/2.76.0",
        # "vcpkg_package": "glib",
        # "prebuilt_path": "/opt/libs/{target_name}",
        # "source_url": "https://...",
    }},"#,
            packages = packages.join(", ")
        ));
    }

    lines.push("}".to_string());
    lines.push(String::new());

    // Add the resolver function
    lines.push(
        r#"def resolve_dep(name):
    """Resolve a dependency based on configuration.

    Args:
        name: The dependency name (e.g., "glib")

    Returns:
        A label pointing to the resolved dependency target.
    """
    config = DEPS_CONFIG.get(name, {})
    strategy = config.get("strategy", DEFAULT_STRATEGY)

    if strategy == "system":
        # Use new_local_repository wrapper from system_deps module extension
        return "@system_{}//:{}".format(name, name)
    elif strategy == "source":
        return "//third_party:{}_source".format(name)
    elif strategy == "conan":
        return "@conan_{}//:{}".format(name, name)
    elif strategy == "vcpkg":
        return "@vcpkg_{}//:{}".format(name, name)
    elif strategy == "prebuilt":
        return "//third_party:{}_prebuilt".format(name)
    elif strategy == "bazelle":
        # Use bazelle/gazelle_cc generated BUILD files
        return "@{}_src//:{}".format(name, name)
    elif strategy == "custom":
        # Users implement custom_resolve_dep in config_custom.bzl
        return custom_resolve_dep(name, config)
    else:
        fail("Unknown dependency strategy: " + strategy)

def custom_resolve_dep(name, config):
    """Override this function in config_custom.bzl for custom resolution.

    Example config_custom.bzl:
        def custom_resolve_dep(name, config):
            return "@my_internal_repo//libs:" + name
    """
    fail("Custom resolution not implemented. Create config_custom.bzl and implement custom_resolve_dep()")"#
            .to_string(),
    );

    lines.join("\n")
}

/// Generate the third_party/source.bzl file for building from source.
pub fn generate_source_bzl(pkg_config_modules: &[PkgConfigModule]) -> String {
    let mut lines = vec![
        r#""""Build third-party dependencies from source using rules_foreign_cc.

This provides hermetic, reproducible builds but requires more setup.
"""

load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake", "configure_make", "meson")

# Source URLs and versions for each dependency.
# Update these to use specific versions for reproducibility.
SOURCES = {"#
            .to_string(),
    ];

    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        lines.push(format!(
            r#"    "{target_name}": {{
        # "url": "https://...",
        # "sha256": "...",
        # "strip_prefix": "...",
        # "build_system": "cmake",  # or "autotools", "meson"
    }},"#
        ));
    }

    lines.push("}".to_string());
    lines.push(String::new());

    lines.push(
        r#"def setup_source_deps():
    """Set up http_archive rules for source dependencies.

    Call this from your MODULE.bazel or WORKSPACE.
    """
    for name, config in SOURCES.items():
        if "url" not in config:
            continue
        native.http_archive(
            name = name + "_src",
            urls = [config["url"]],
            sha256 = config.get("sha256", ""),
            strip_prefix = config.get("strip_prefix", ""),
        )

def build_from_source(name):
    """Generate build rules for a source dependency."""
    config = SOURCES.get(name, {})
    build_system = config.get("build_system", "cmake")

    if build_system == "cmake":
        cmake(
            name = name + "_source",
            lib_source = "@{}_src//:all".format(name),
            # Add cmake options as needed
        )
    elif build_system == "autotools":
        configure_make(
            name = name + "_source",
            lib_source = "@{}_src//:all".format(name),
        )
    elif build_system == "meson":
        meson(
            name = name + "_source",
            lib_source = "@{}_src//:all".format(name),
        )"#
            .to_string(),
    );

    lines.join("\n")
}

/// Detected system library info from pkg-config.
#[derive(Debug, Clone)]
pub struct SystemLibInfo {
    /// Library name (e.g., "glib")
    pub name: String,
    /// pkg-config package names
    pub packages: Vec<String>,
    /// Detected install prefix (e.g., /opt/homebrew/Cellar/glib/2.86.3)
    pub prefix: Option<String>,
    /// Include directories relative to prefix
    pub include_dirs: Vec<String>,
    /// Library directories relative to prefix
    pub lib_dirs: Vec<String>,
    /// Library names to link
    pub libs: Vec<String>,
}

/// Probe pkg-config to get detailed library info.
pub fn probe_system_lib(packages: &[String]) -> Option<SystemLibInfo> {
    use std::process::Command;

    let base_packages: Vec<&str> = packages
        .iter()
        .map(|p| p.split(">=").next().unwrap_or(p).trim())
        .collect();

    // Get prefix
    let prefix_output = Command::new("pkg-config")
        .args(["--variable=prefix"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !prefix_output.status.success() {
        return None;
    }

    let prefix = String::from_utf8_lossy(&prefix_output.stdout)
        .trim()
        .to_string();

    if prefix.is_empty() {
        return None;
    }

    // Get cflags to extract include dirs
    let cflags_output = Command::new("pkg-config")
        .args(["--cflags"])
        .args(&base_packages)
        .output()
        .ok()?;

    let cflags_str = String::from_utf8_lossy(&cflags_output.stdout);
    let include_dirs: Vec<String> = cflags_str
        .split_whitespace()
        .filter_map(|f| f.strip_prefix("-I"))
        .map(|p| {
            // Try to make path relative to prefix
            p.strip_prefix(&prefix)
                .map(|rel| rel.trim_start_matches('/').to_string())
                .unwrap_or_else(|| p.to_string())
        })
        .collect();

    // Get libs
    let libs_output = Command::new("pkg-config")
        .args(["--libs"])
        .args(&base_packages)
        .output()
        .ok()?;

    let libs_str = String::from_utf8_lossy(&libs_output.stdout);
    let mut libs = Vec::new();
    let mut lib_dirs = Vec::new();

    for flag in libs_str.split_whitespace() {
        if let Some(lib) = flag.strip_prefix("-l") {
            libs.push(lib.to_string());
        } else if let Some(dir) = flag.strip_prefix("-L") {
            let rel_dir = dir.strip_prefix(&prefix)
                .map(|rel| rel.trim_start_matches('/').to_string())
                .unwrap_or_else(|| dir.to_string());
            lib_dirs.push(rel_dir);
        }
    }

    Some(SystemLibInfo {
        name: base_packages.first()?.to_string(),
        packages: packages.to_vec(),
        prefix: Some(prefix),
        include_dirs,
        lib_dirs,
        libs,
    })
}

/// Generate system_deps.bzl module extension for wrapping system libraries.
pub fn generate_system_deps_bzl(pkg_config_modules: &[PkgConfigModule]) -> String {
    let mut lines = vec![
        r#""""Module extension for system library dependencies.

This uses new_local_repository to wrap system-installed libraries,
making them available within Bazel's execution root.

NOTE: These paths are detected from pkg-config during migration.
      Adjust SYSTEM_LIBS paths for your target system.
"""

# System library configurations.
# Each entry maps a library name to its system path and structure.
SYSTEM_LIBS = {"#.to_string(),
    ];

    // Probe each package and generate config
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");

        if let Some(info) = probe_system_lib(&pkg.packages) {
            let prefix = info.prefix.as_deref().unwrap_or("/usr/local");
            let include_dirs: Vec<_> = info.include_dirs.iter()
                .map(|d| format!("\"{}\"", d))
                .collect();
            let lib_dirs: Vec<_> = info.lib_dirs.iter()
                .map(|d| format!("\"{}\"", d))
                .collect();
            let libs: Vec<_> = info.libs.iter()
                .map(|l| format!("\"{}\"", l))
                .collect();

            lines.push(format!(
                r#"    "{target_name}": {{
        "path": "{prefix}",
        "include_dirs": [{includes}],
        "lib_dirs": [{lib_dirs}],
        "libs": [{libs}],
    }},"#,
                includes = include_dirs.join(", "),
                lib_dirs = lib_dirs.join(", "),
                libs = libs.join(", "),
            ));
        } else {
            // Fallback for unavailable packages
            lines.push(format!(
                r#"    "{target_name}": {{
        # TODO: pkg-config not available. Configure manually:
        # "path": "/usr/local",
        # "include_dirs": ["include"],
        # "libs": ["{target_name}"],
    }},"#
            ));
        }
    }

    lines.push("}".to_string());
    lines.push(String::new());

    // Add the module extension implementation
    lines.push(r#"def _system_lib_repo_impl(repository_ctx):
    """Implementation of system library repository rule."""
    name = repository_ctx.attr.lib_name
    path = repository_ctx.attr.path
    include_dirs = repository_ctx.attr.include_dirs
    lib_dirs = repository_ctx.attr.lib_dirs
    libs = repository_ctx.attr.libs

    # Symlink the system library directory
    repository_ctx.symlink(path, "root")

    # Generate BUILD file content
    hdrs_patterns = []
    for d in include_dirs:
        if d.startswith("/"):
            # Absolute path - can't glob, skip
            continue
        hdrs_patterns.append('"root/{}/**/*.h"'.format(d))

    hdrs_glob = "glob([{}], allow_empty = True)".format(", ".join(hdrs_patterns)) if hdrs_patterns else "[]"
    includes_list = ", ".join(['"root/{}"'.format(d) for d in include_dirs if not d.startswith("/")])

    # Build linkopts: -L for library directories, -l for libraries
    # NOTE: We use absolute paths since we're already non-hermetic with system libs
    linkopts = []
    for d in lib_dirs:
        if d.startswith("/"):
            # Already absolute
            linkopts.append('"-L{}"'.format(d))
        else:
            # Relative to prefix - construct absolute path
            linkopts.append('"-L{}/{}"'.format(path, d))
    for l in libs:
        linkopts.append('"-l{}"'.format(l))
    linkopts_list = ", ".join(linkopts)

    build_content = '''
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "{name}",
    hdrs = {hdrs},
    includes = [{includes}],
    linkopts = [{linkopts}],
    visibility = ["//visibility:public"],
)
'''.format(
        name = name,
        hdrs = hdrs_glob,
        includes = includes_list,
        linkopts = linkopts_list,
    )

    repository_ctx.file("BUILD.bazel", build_content)

_system_lib_repo = repository_rule(
    implementation = _system_lib_repo_impl,
    attrs = {
        "lib_name": attr.string(mandatory = True),
        "path": attr.string(mandatory = True),
        "include_dirs": attr.string_list(default = ["include"]),
        "lib_dirs": attr.string_list(default = ["lib"]),
        "libs": attr.string_list(default = []),
    },
    local = True,  # Depends on local system state
)

def _stub_repo_impl(repository_ctx):
    """Create a stub repository for unavailable packages."""
    name = repository_ctx.attr.lib_name
    build_content = '''
load("@rules_cc//cc:defs.bzl", "cc_library")

# Stub library - package not available via pkg-config during migration
# Configure the real path in system_deps.bzl SYSTEM_LIBS
cc_library(
    name = "{name}",
    visibility = ["//visibility:public"],
)
'''.format(name = name)
    repository_ctx.file("BUILD.bazel", build_content)

_stub_repo = repository_rule(
    implementation = _stub_repo_impl,
    attrs = {
        "lib_name": attr.string(mandatory = True),
    },
)

def _system_deps_impl(module_ctx):
    """Implementation of system_deps module extension."""
    for name, config in SYSTEM_LIBS.items():
        if "path" not in config:
            # Create stub repo for unavailable packages
            _stub_repo(
                name = "system_" + name,
                lib_name = name,
            )
            continue

        _system_lib_repo(
            name = "system_" + name,
            lib_name = name,
            path = config["path"],
            include_dirs = config.get("include_dirs", ["include"]),
            lib_dirs = config.get("lib_dirs", ["lib"]),
            libs = config.get("libs", [name]),
        )

system_deps = module_extension(
    implementation = _system_deps_impl,
)"#.to_string());

    lines.join("\n")
}

/// Detected pkg-config flags for a package.
#[derive(Debug, Clone, Default)]
pub struct PkgConfigFlags {
    /// Compiler flags (from --cflags)
    pub cflags: Vec<String>,
    /// Linker flags (from --libs)
    pub libs: Vec<String>,
}

/// Probe pkg-config to get actual flags for packages.
/// Returns None if pkg-config is not available or the package is not found.
pub fn probe_pkg_config(packages: &[String]) -> Option<PkgConfigFlags> {
    use std::process::Command;

    // Extract base package names (remove version constraints)
    let base_packages: Vec<&str> = packages
        .iter()
        .map(|p| p.split(">=").next().unwrap_or(p).trim())
        .collect();

    // Try to get cflags
    let cflags_output = Command::new("pkg-config")
        .args(["--cflags"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !cflags_output.status.success() {
        return None;
    }

    let cflags_str = String::from_utf8_lossy(&cflags_output.stdout);
    let cflags: Vec<String> = cflags_str
        .split_whitespace()
        .map(String::from)
        .collect();

    // Try to get libs
    let libs_output = Command::new("pkg-config")
        .args(["--libs"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !libs_output.status.success() {
        return None;
    }

    let libs_str = String::from_utf8_lossy(&libs_output.stdout);
    let libs: Vec<String> = libs_str
        .split_whitespace()
        .map(String::from)
        .collect();

    Some(PkgConfigFlags { cflags, libs })
}

/// Generate linkopts for system libraries.
fn generate_system_linkopts(packages: &[String]) -> Vec<String> {
    let mut linkopts = Vec::new();

    for pkg in packages {
        let base = pkg.split(">=").next().unwrap_or(pkg).trim();

        match base {
            "glib-2.0" => linkopts.push("-lglib-2.0".to_string()),
            "gobject-2.0" => linkopts.push("-lgobject-2.0".to_string()),
            "gio-2.0" => linkopts.push("-lgio-2.0".to_string()),
            "gthread-2.0" => linkopts.push("-lgthread-2.0".to_string()),
            "gmodule-2.0" => linkopts.push("-lgmodule-2.0".to_string()),
            "libpeas-1.0" => linkopts.push("-lpeas-1.0".to_string()),
            "libdnf" => linkopts.push("-ldnf".to_string()),
            "smartcols" => linkopts.push("-lsmartcols".to_string()),
            "libcurl" | "curl" => linkopts.push("-lcurl".to_string()),
            "openssl" => {
                linkopts.push("-lssl".to_string());
                linkopts.push("-lcrypto".to_string());
            }
            "zlib" => linkopts.push("-lz".to_string()),
            "libxml-2.0" => linkopts.push("-lxml2".to_string()),
            _ => {
                let lib_name = base
                    .strip_prefix("lib")
                    .unwrap_or(base)
                    .split('-')
                    .next()
                    .unwrap_or(base);
                linkopts.push(format!("-l{lib_name}"));
            }
        }
    }

    linkopts
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_system_linkopts() {
        let packages = vec!["glib-2.0>=2.44.0".to_string()];
        let linkopts = generate_system_linkopts(&packages);
        assert_eq!(linkopts, vec!["-lglib-2.0"]);
    }

    #[test]
    fn test_deps_strategy_default() {
        let config = ThirdPartyConfig::default();
        assert_eq!(config.default_strategy, DepsStrategy::System);
    }
}
