//! Third-party dependency configuration and generation.
//!
//! This module generates extensible BUILD files for third-party dependencies,
//! supporting multiple resolution strategies:
//!
//! - `system`: Use system-installed libraries via new_local_repository (non-hermetic)
//! - `source`: Build from source using rules_foreign_cc (hermetic)
//! - `conan`: Use Conan package manager
//! - `vcpkg`: Use vcpkg package manager
//! - `prebuilt`: Use pre-built libraries from filesystem
//! - `bazelle`: Use bazelle/gazelle_cc to generate BUILD files
//! - `custom`: User-defined resolution

use crate::starlark::{Alias, CcLibrary, Cmake, ConfigureMake, FunctionCall, Meson};
use rebaze_cmake::PkgConfigModule;
use std::collections::{BTreeMap, BTreeSet};

/// Deduplicate pkg-config modules by their normalized target name.
///
/// Returns a new `Vec` with duplicates removed, preserving the order of first occurrence.
/// Uses BTreeSet for deterministic deduplication behavior.
pub fn deduplicate_modules(modules: &[PkgConfigModule]) -> Vec<PkgConfigModule> {
    let mut seen = BTreeSet::new();
    modules
        .iter()
        .filter(|pkg| {
            let target_name = pkg.prefix.to_lowercase().replace('-', "_");
            seen.insert(target_name)
        })
        .cloned()
        .collect()
}

/// Dependency resolution strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DepsStrategy {
    /// Use system libraries via new_local_repository (non-hermetic, but works)
    /// This is the default since it works out of the box when deps are installed.
    #[default]
    System,
    /// Build from source using rules_foreign_cc (hermetic, recommended for production)
    Source,
    /// Use Conan package manager
    Conan,
    /// Use vcpkg package manager
    Vcpkg,
    /// Use pre-built libraries from filesystem
    Prebuilt,
    /// Use bazelle/gazelle_cc to generate BUILD files for deps
    Bazelle,
    /// User provides custom resolution
    Custom,
}

/// Configuration for third-party dependency generation.
#[derive(Debug, Clone, Default)]
pub struct ThirdPartyConfig {
    /// Default strategy for resolving dependencies
    pub default_strategy: DepsStrategy,
    /// Path to prebuilt libraries (for Prebuilt strategy)
    pub prebuilt_path: Option<String>,
    /// Conan profile to use
    pub conan_profile: Option<String>,
    /// vcpkg triplet to use
    pub vcpkg_triplet: Option<String>,
}

/// Generate the third_party/BUILD.bazel file.
#[allow(clippy::option_if_let_else)]
pub fn generate_build_file(
    pkg_config_modules: &[PkgConfigModule],
    _config: &ThirdPartyConfig,
) -> String {
    // Check if any pkg-config packages are available on this system
    let any_pkg_config_available = pkg_config_modules
        .iter()
        .any(|pkg| probe_pkg_config(&pkg.packages).is_some());

    let pkg_config_note = if any_pkg_config_available {
        "# NOTE: System library flags were detected via pkg-config during migration.\n#       These paths are system-specific and may need adjustment on other machines."
    } else {
        "# NOTE: pkg-config was not available during migration.\n#       You need to add copts for include paths. Run: pkg-config --cflags <package>"
    };

    let mut lines = vec![
        format!(
            r#"# Third-party dependencies - Generated by rebaze
#
# This file provides extensible dependency resolution. Edit third_party/config.bzl
# to configure how dependencies are resolved.
#
# Supported strategies:
#   - system:   Use system libraries via pkg-config (non-hermetic)
#   - source:   Build from source with rules_foreign_cc (hermetic, recommended)
#   - conan:    Use Conan package manager
#   - vcpkg:    Use vcpkg package manager
#   - prebuilt: Use pre-compiled libraries from filesystem
#   - custom:   Implement your own resolution in config.bzl
#
{pkg_config_note}

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//third_party:config.bzl", "DEPS_CONFIG", "resolve_dep")

package(default_visibility = ["//visibility:public"])"#
        ),
        String::new(),
    ];

    // Generate an alias for each dependency that uses the configured resolver
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages_str = pkg.packages.join(", ");

        let alias = Alias {
            name: target_name.clone(),
            actual: FunctionCall {
                name: "resolve_dep",
                args: vec![target_name],
            },
        };

        lines.push(format!("# {} -> {}", pkg.prefix, packages_str));
        if let Ok(alias_str) = crate::starlark::serde_starlark::to_string(&alias) {
            lines.push(alias_str);
        }
        lines.push(String::new());
    }

    // Generate fallback cc_library rules for system strategy
    lines.push("# ============================================================".to_string());
    lines.push("# System library fallbacks (used when strategy = \"system\")".to_string());
    lines.push("# ============================================================".to_string());
    lines.push(String::new());

    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages_str = pkg.packages.join(", ");

        // Try to detect actual flags from pkg-config
        let detected_flags = probe_pkg_config(&pkg.packages);

        // NOTE: We only include linkopts here, NOT copts with include paths.
        // Include paths must go in .bazelrc as --copt=-isystem/path because
        // rules_cc validates include paths in copts and rejects absolute system paths.

        let (linkopts, needs_todo) = if let Some(ref flags) = detected_flags {
            // Extract only linker flags (not -I or other compiler flags)
            let opts: Vec<String> = flags
                .libs
                .iter()
                .filter(|f| f.starts_with("-l") || f.starts_with("-L"))
                .cloned()
                .collect();
            (opts, false)
        } else {
            // Fallback to guessed linkopts when pkg-config not available
            (generate_system_linkopts(&pkg.packages), true)
        };

        let cc_lib = CcLibrary {
            name: format!("{target_name}_system"),
            linkopts,
            ..Default::default()
        };

        if let Ok(lib_str) = crate::starlark::serde_starlark::to_string(&cc_lib) {
            lines.push(lib_str);
        }

        if needs_todo {
            lines.push("# TODO: pkg-config not available. Add linkopts from:".to_string());
            lines.push(format!("# pkg-config --libs {packages_str}"));
        }

        lines.push(String::new());
    }

    lines.join("\n")
}

/// Generate the third_party/config.bzl file.
pub fn generate_config_bzl(
    pkg_config_modules: &[PkgConfigModule],
    config: &ThirdPartyConfig,
) -> String {
    let default_strategy = match config.default_strategy {
        DepsStrategy::System => "system",
        DepsStrategy::Source => "source",
        DepsStrategy::Conan => "conan",
        DepsStrategy::Vcpkg => "vcpkg",
        DepsStrategy::Prebuilt => "prebuilt",
        DepsStrategy::Bazelle => "bazelle",
        DepsStrategy::Custom => "custom",
    };

    let mut lines = vec![
        format!(
            r#""""Configuration for third-party dependencies.

Edit this file to customize how dependencies are resolved.
"""

# Default resolution strategy for all dependencies.
# Options: "system", "source", "conan", "vcpkg", "prebuilt", "custom"
DEFAULT_STRATEGY = "{default_strategy}"

# Per-dependency configuration.
# Override the strategy or provide additional config for specific deps.
DEPS_CONFIG = {{"#
        ),
    ];

    // Generate config entries for each dependency
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");
        let packages: Vec<_> = pkg
            .packages
            .iter()
            .map(|p| format!("\"{p}\""))
            .collect();

        lines.push(format!(
            r#"    "{target_name}": {{
        "pkg_config": [{packages}],
        # "strategy": "system",  # Override default strategy
        # "conan_package": "glib/2.76.0",
        # "vcpkg_package": "glib",
        # "prebuilt_path": "/opt/libs/{target_name}",
        # "source_url": "https://...",
    }},"#,
            packages = packages.join(", ")
        ));
    }

    lines.push("}".to_string());
    lines.push(String::new());

    // Add the resolver function
    lines.push(
        r#"def resolve_dep(name):
    """Resolve a dependency based on configuration.

    Args:
        name: The dependency name (e.g., "glib")

    Returns:
        A label pointing to the resolved dependency target.
    """
    config = DEPS_CONFIG.get(name, {})
    strategy = config.get("strategy", DEFAULT_STRATEGY)

    if strategy == "system":
        # Use new_local_repository wrapper from system_deps module extension
        return "@system_{}//:{}".format(name, name)
    elif strategy == "source":
        return "//third_party:{}_source".format(name)
    elif strategy == "conan":
        return "@conan_{}//:{}".format(name, name)
    elif strategy == "vcpkg":
        return "@vcpkg_{}//:{}".format(name, name)
    elif strategy == "prebuilt":
        return "//third_party:{}_prebuilt".format(name)
    elif strategy == "bazelle":
        # Use bazelle/gazelle_cc generated BUILD files
        return "@{}_src//:{}".format(name, name)
    elif strategy == "custom":
        # Users implement custom_resolve_dep in config_custom.bzl
        return custom_resolve_dep(name, config)
    else:
        fail("Unknown dependency strategy: " + strategy)

def custom_resolve_dep(name, config):
    """Override this function in config_custom.bzl for custom resolution.

    Example config_custom.bzl:
        def custom_resolve_dep(name, config):
            return "@my_internal_repo//libs:" + name
    """
    fail("Custom resolution not implemented. Create config_custom.bzl and implement custom_resolve_dep()")"#
            .to_string(),
    );

    lines.join("\n")
}

/// Known package metadata for common libraries.
/// This provides default URLs, versions, and build system info.
fn get_known_package_info(pkg_name: &str) -> Option<KnownPackageInfo> {
    match pkg_name {
        "glib" | "glib-2.0" => Some(KnownPackageInfo {
            name: "glib",
            version: "2.82.4",
            url: "https://download.gnome.org/sources/glib/2.82/glib-2.82.4.tar.xz",
            sha256: "937f1312d7a883e6fdd0f75ed28de2f9e4fc2ee83fece0ab46a5153d5c34ce93",
            strip_prefix: "glib-2.82.4",
            build_system: "meson",
            out_libs: vec!["libglib-2.0.a"],
            out_shared_libs: vec!["libglib-2.0.so", "libglib-2.0.dylib"],
            deps: vec!["pcre2", "libffi", "zlib"],
            meson_options: vec![
                "-Dtests=false",
                "-Dglib_debug=disabled",
                "-Dintrospection=disabled",
            ],
        }),
        "gobject" | "gobject-2.0" => Some(KnownPackageInfo {
            name: "gobject",
            version: "2.82.4",
            url: "https://download.gnome.org/sources/glib/2.82/glib-2.82.4.tar.xz",
            sha256: "937f1312d7a883e6fdd0f75ed28de2f9e4fc2ee83fece0ab46a5153d5c34ce93",
            strip_prefix: "glib-2.82.4",
            build_system: "meson",
            out_libs: vec!["libgobject-2.0.a"],
            out_shared_libs: vec!["libgobject-2.0.so", "libgobject-2.0.dylib"],
            deps: vec!["glib", "libffi"],
            meson_options: vec!["-Dtests=false"],
        }),
        "pcre2" => Some(KnownPackageInfo {
            name: "pcre2",
            version: "10.44",
            url: "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.gz",
            sha256: "d34f02e113cf7193f1b06f1c26c1f8e7fa6e8a9fe1c3b1c29e579f5a6a6e8a19",
            strip_prefix: "pcre2-10.44",
            build_system: "cmake",
            out_libs: vec!["libpcre2-8.a"],
            out_shared_libs: vec![],
            deps: vec![],
            meson_options: vec![],
        }),
        "zlib" => Some(KnownPackageInfo {
            name: "zlib",
            version: "1.3.1",
            url: "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz",
            sha256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23",
            strip_prefix: "zlib-1.3.1",
            build_system: "cmake",
            out_libs: vec!["libz.a"],
            out_shared_libs: vec![],
            deps: vec![],
            meson_options: vec![],
        }),
        "libffi" => Some(KnownPackageInfo {
            name: "libffi",
            version: "3.4.6",
            url: "https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz",
            sha256: "b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e",
            strip_prefix: "libffi-3.4.6",
            build_system: "autotools",
            out_libs: vec!["libffi.a"],
            out_shared_libs: vec![],
            deps: vec![],
            meson_options: vec![],
        }),
        _ => None,
    }
}

/// Metadata for known packages that can be built from source.
/// Fields like `version` and `out_shared_libs` are reserved for future use.
#[allow(dead_code)]
struct KnownPackageInfo {
    name: &'static str,
    version: &'static str,
    url: &'static str,
    sha256: &'static str,
    strip_prefix: &'static str,
    build_system: &'static str,
    out_libs: Vec<&'static str>,
    out_shared_libs: Vec<&'static str>,
    deps: Vec<&'static str>,
    meson_options: Vec<&'static str>,
}

/// Generate the third_party/source.bzl file for building from source.
#[allow(clippy::too_many_lines)]
pub fn generate_source_bzl(pkg_config_modules: &[PkgConfigModule]) -> String {
    let mut lines = vec![
        r#""""Build third-party dependencies from source using rules_foreign_cc.

This provides hermetic, reproducible builds but requires more setup.

Usage:
  1. In MODULE.bazel, use the source_deps extension:
     source_deps = use_extension("//third_party:source.bzl", "source_deps")
     use_repo(source_deps, "glib_src", "pcre2_src", ...)

  2. In third_party/config.bzl, set strategy to "source":
     DEFAULT_STRATEGY = "source"

  3. Build targets will be available as //third_party:<name>_source
"""

load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake", "configure_make", "meson")

# Source configurations for each dependency.
# These are populated with known good defaults where available.
SOURCES = {"#
            .to_string(),
    ];

    // Collect all unique packages including transitive deps
    let mut all_packages = std::collections::BTreeSet::new();
    for pkg in pkg_config_modules {
        let name = pkg.prefix.to_lowercase().replace('-', "_");
        all_packages.insert(name.clone());

        // Add known transitive deps
        if let Some(info) = get_known_package_info(&name) {
            for dep in info.deps {
                all_packages.insert(dep.to_string());
            }
        }
    }

    for pkg_name in &all_packages {
        if let Some(info) = get_known_package_info(pkg_name) {
            let deps_str = if info.deps.is_empty() {
                String::new()
            } else {
                format!(
                    "\n        \"deps\": [{}],",
                    info.deps.iter().map(|d| format!("\"{d}\"")).collect::<Vec<_>>().join(", ")
                )
            };

            let meson_opts_str = if info.meson_options.is_empty() {
                String::new()
            } else {
                format!(
                    "\n        \"meson_options\": [{}],",
                    info.meson_options.iter().map(|o| format!("\"{o}\"")).collect::<Vec<_>>().join(", ")
                )
            };

            let out_libs_str = info.out_libs.iter()
                .map(|l| format!("\"{l}\""))
                .collect::<Vec<_>>()
                .join(", ");

            lines.push(format!(
                r#"    "{name}": {{
        "url": "{url}",
        "sha256": "{sha256}",
        "strip_prefix": "{strip_prefix}",
        "build_system": "{build_system}",
        "out_static_libs": [{out_libs}],{deps}{meson_opts}
    }},"#,
                name = info.name,
                url = info.url,
                sha256 = info.sha256,
                strip_prefix = info.strip_prefix,
                build_system = info.build_system,
                out_libs = out_libs_str,
                deps = deps_str,
                meson_opts = meson_opts_str,
            ));
        } else {
            // Unknown package - generate placeholder
            lines.push(format!(
                r#"    "{pkg_name}": {{
        # TODO: Configure source build for {pkg_name}
        # "url": "https://...",
        # "sha256": "...",
        # "strip_prefix": "...",
        # "build_system": "cmake",  # or "autotools", "meson"
        # "out_static_libs": ["lib{pkg_name}.a"],
    }},"#
            ));
        }
    }

    lines.push("}".to_string());
    lines.push(String::new());

    // Add the module extension for downloading sources
    lines.push(r#"def _source_repo_impl(repository_ctx):
    """Download and prepare source repository."""
    repository_ctx.download_and_extract(
        url = repository_ctx.attr.url,
        sha256 = repository_ctx.attr.sha256,
        stripPrefix = repository_ctx.attr.strip_prefix,
    )

    # Create BUILD.bazel that exports all sources
    repository_ctx.file("BUILD.bazel", '''
filegroup(
    name = "all",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
''')

_source_repo = repository_rule(
    implementation = _source_repo_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(default = ""),
        "strip_prefix": attr.string(default = ""),
    },
)

def _source_deps_impl(module_ctx):
    """Download all configured source dependencies."""
    for name, config in SOURCES.items():
        if "url" not in config:
            continue
        _source_repo(
            name = name + "_src",
            url = config["url"],
            sha256 = config.get("sha256", ""),
            strip_prefix = config.get("strip_prefix", ""),
        )

source_deps = module_extension(
    implementation = _source_deps_impl,
)"#.to_string());

    lines.join("\n")
}

/// Generate BUILD targets for source dependencies.
pub fn generate_source_build_targets(pkg_config_modules: &[PkgConfigModule]) -> String {
    let mut lines = vec![
        r#"# Source build targets using rules_foreign_cc
# These build dependencies from source for hermetic builds.

load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake", "configure_make", "meson")
load("//third_party:source.bzl", "SOURCES")
"#.to_string(),
    ];

    // Collect all packages including transitive deps
    let mut all_packages = std::collections::BTreeSet::new();
    for pkg in pkg_config_modules {
        let name = pkg.prefix.to_lowercase().replace('-', "_");
        all_packages.insert(name.clone());
        if let Some(info) = get_known_package_info(&name) {
            for dep in info.deps {
                all_packages.insert(dep.to_string());
            }
        }
    }

    for pkg_name in &all_packages {
        if let Some(info) = get_known_package_info(pkg_name) {
            let name = format!("{}_source", info.name);
            let lib_source = format!("@{}_src//:all", info.name);
            let deps: Vec<String> = info
                .deps
                .iter()
                .map(|d| format!(":{d}_source"))
                .collect();

            let rule_str = match info.build_system {
                "meson" => {
                    let options: BTreeMap<String, String> = info
                        .meson_options
                        .iter()
                        .map(|o| {
                            let parts: Vec<&str> =
                                o.trim_start_matches('-').splitn(2, '=').collect();
                            if parts.len() == 2 {
                                (parts[0].to_string(), parts[1].to_string())
                            } else {
                                (parts[0].to_string(), "true".to_string())
                            }
                        })
                        .collect();

                    let rule = Meson::new(name, lib_source)
                        .with_static_libs(info.out_libs.clone())
                        .with_options(options)
                        .with_deps(deps)
                        .with_visibility_public();
                    crate::starlark::serde_starlark::to_string(&rule).ok()
                }
                "cmake" => {
                    let rule = Cmake::new(name, lib_source)
                        .with_static_libs(info.out_libs.clone())
                        .with_deps(deps)
                        .with_visibility_public();
                    crate::starlark::serde_starlark::to_string(&rule).ok()
                }
                "autotools" => {
                    let rule = ConfigureMake::new(name, lib_source)
                        .with_static_libs(info.out_libs.clone())
                        .with_deps(deps)
                        .with_visibility_public();
                    crate::starlark::serde_starlark::to_string(&rule).ok()
                }
                _ => None,
            };

            if let Some(rule) = rule_str {
                lines.push(format!("\n{rule}"));
            }
        } else {
            // Unknown package - generate placeholder
            lines.push(format!(
                r#"
# TODO: Configure source build for {pkg_name}
# Uncomment and adjust after configuring SOURCES["{pkg_name}"] in source.bzl
#
# cmake(
#     name = "{pkg_name}_source",
#     lib_source = "@{pkg_name}_src//:all",
#     out_static_libs = ["lib{pkg_name}.a"],
#     visibility = ["//visibility:public"],
# )
"#
            ));
        }
    }

    lines.join("\n")
}

/// Detected system library info from pkg-config.
#[derive(Debug, Clone)]
pub struct SystemLibInfo {
    /// Library name (e.g., "glib")
    pub name: String,
    /// pkg-config package names
    pub packages: Vec<String>,
    /// Detected install prefix (e.g., /opt/homebrew/Cellar/glib/2.86.3)
    pub prefix: Option<String>,
    /// Include directories relative to prefix
    pub include_dirs: Vec<String>,
    /// Library directories relative to prefix
    pub lib_dirs: Vec<String>,
    /// Library names to link
    pub libs: Vec<String>,
}

/// Probe pkg-config to get detailed library info.
pub fn probe_system_lib(packages: &[String]) -> Option<SystemLibInfo> {
    use std::process::Command;

    let base_packages: Vec<&str> = packages
        .iter()
        .map(|p| p.split(">=").next().unwrap_or(p).trim())
        .collect();

    // Get prefix
    let prefix_output = Command::new("pkg-config")
        .args(["--variable=prefix"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !prefix_output.status.success() {
        return None;
    }

    let prefix = String::from_utf8_lossy(&prefix_output.stdout)
        .trim()
        .to_string();

    if prefix.is_empty() {
        return None;
    }

    // Get cflags to extract include dirs
    let cflags_output = Command::new("pkg-config")
        .args(["--cflags"])
        .args(&base_packages)
        .output()
        .ok()?;

    let cflags_str = String::from_utf8_lossy(&cflags_output.stdout);
    let include_dirs: Vec<String> = cflags_str
        .split_whitespace()
        .filter_map(|f| f.strip_prefix("-I"))
        .map(|p| {
            // Try to make path relative to prefix
            p.strip_prefix(&prefix).map_or_else(|| p.to_string(), |rel| rel.trim_start_matches('/').to_string())
        })
        .collect();

    // Get libs
    let libs_output = Command::new("pkg-config")
        .args(["--libs"])
        .args(&base_packages)
        .output()
        .ok()?;

    let libs_str = String::from_utf8_lossy(&libs_output.stdout);
    let mut libs = Vec::new();
    let mut lib_dirs = Vec::new();

    for flag in libs_str.split_whitespace() {
        if let Some(lib) = flag.strip_prefix("-l") {
            libs.push(lib.to_string());
        } else if let Some(dir) = flag.strip_prefix("-L") {
            let rel_dir = dir.strip_prefix(&prefix).map_or_else(|| dir.to_string(), |rel| rel.trim_start_matches('/').to_string());
            lib_dirs.push(rel_dir);
        }
    }

    Some(SystemLibInfo {
        name: (*base_packages.first()?).to_string(),
        packages: packages.to_vec(),
        prefix: Some(prefix),
        include_dirs,
        lib_dirs,
        libs,
    })
}

/// Generate system_deps.bzl module extension for wrapping system libraries.
#[allow(clippy::too_many_lines)]
pub fn generate_system_deps_bzl(pkg_config_modules: &[PkgConfigModule]) -> String {
    let mut lines = vec![
        r#""""Module extension for system library dependencies.

This uses new_local_repository to wrap system-installed libraries,
making them available within Bazel's execution root.

NOTE: These paths are detected from pkg-config during migration.
      Adjust SYSTEM_LIBS paths for your target system.
"""

# System library configurations.
# Each entry maps a library name to its system path and structure.
SYSTEM_LIBS = {"#.to_string(),
    ];

    // Probe each package and generate config
    for pkg in pkg_config_modules {
        let target_name = pkg.prefix.to_lowercase().replace('-', "_");

        if let Some(info) = probe_system_lib(&pkg.packages) {
            let prefix = info.prefix.as_deref().unwrap_or("/usr/local");
            let include_dirs: Vec<_> = info.include_dirs.iter()
                .map(|d| format!("\"{d}\""))
                .collect();
            let lib_dirs: Vec<_> = info.lib_dirs.iter()
                .map(|d| format!("\"{d}\""))
                .collect();
            let libs: Vec<_> = info.libs.iter()
                .map(|l| format!("\"{l}\""))
                .collect();

            lines.push(format!(
                r#"    "{target_name}": {{
        "path": "{prefix}",
        "include_dirs": [{includes}],
        "lib_dirs": [{lib_dirs}],
        "libs": [{libs}],
    }},"#,
                includes = include_dirs.join(", "),
                lib_dirs = lib_dirs.join(", "),
                libs = libs.join(", "),
            ));
        } else {
            // Fallback for unavailable packages
            lines.push(format!(
                r#"    "{target_name}": {{
        # TODO: pkg-config not available. Configure manually:
        # "path": "/usr/local",
        # "include_dirs": ["include"],
        # "libs": ["{target_name}"],
    }},"#
            ));
        }
    }

    lines.push("}".to_string());
    lines.push(String::new());

    // Add the module extension implementation
    lines.push(r#"def _system_lib_repo_impl(repository_ctx):
    """Implementation of system library repository rule."""
    name = repository_ctx.attr.lib_name
    path = repository_ctx.attr.path
    include_dirs = repository_ctx.attr.include_dirs
    lib_dirs = repository_ctx.attr.lib_dirs
    libs = repository_ctx.attr.libs

    # Symlink the system library directory
    repository_ctx.symlink(path, "root")

    # Generate BUILD file content
    hdrs_patterns = []
    for d in include_dirs:
        if d.startswith("/"):
            # Absolute path - can't glob, skip
            continue
        hdrs_patterns.append('"root/{}/**/*.h"'.format(d))

    hdrs_glob = "glob([{}], allow_empty = True)".format(", ".join(hdrs_patterns)) if hdrs_patterns else "[]"
    includes_list = ", ".join(['"root/{}"'.format(d) for d in include_dirs if not d.startswith("/")])

    # Build linkopts: -L for library directories, -l for libraries
    # NOTE: We use absolute paths since we're already non-hermetic with system libs
    linkopts = []
    for d in lib_dirs:
        if d.startswith("/"):
            # Already absolute
            linkopts.append('"-L{}"'.format(d))
        else:
            # Relative to prefix - construct absolute path
            linkopts.append('"-L{}/{}"'.format(path, d))
    for l in libs:
        linkopts.append('"-l{}"'.format(l))
    linkopts_list = ", ".join(linkopts)

    build_content = '''
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "{name}",
    hdrs = {hdrs},
    includes = [{includes}],
    linkopts = [{linkopts}],
    visibility = ["//visibility:public"],
)
'''.format(
        name = name,
        hdrs = hdrs_glob,
        includes = includes_list,
        linkopts = linkopts_list,
    )

    repository_ctx.file("BUILD.bazel", build_content)

_system_lib_repo = repository_rule(
    implementation = _system_lib_repo_impl,
    attrs = {
        "lib_name": attr.string(mandatory = True),
        "path": attr.string(mandatory = True),
        "include_dirs": attr.string_list(default = ["include"]),
        "lib_dirs": attr.string_list(default = ["lib"]),
        "libs": attr.string_list(default = []),
    },
    local = True,  # Depends on local system state
)

def _stub_repo_impl(repository_ctx):
    """Create a stub repository for unavailable packages."""
    name = repository_ctx.attr.lib_name
    build_content = '''
load("@rules_cc//cc:defs.bzl", "cc_library")

# Stub library - package not available via pkg-config during migration
# Configure the real path in system_deps.bzl SYSTEM_LIBS
cc_library(
    name = "{name}",
    visibility = ["//visibility:public"],
)
'''.format(name = name)
    repository_ctx.file("BUILD.bazel", build_content)

_stub_repo = repository_rule(
    implementation = _stub_repo_impl,
    attrs = {
        "lib_name": attr.string(mandatory = True),
    },
)

def _system_deps_impl(module_ctx):
    """Implementation of system_deps module extension."""
    for name, config in SYSTEM_LIBS.items():
        if "path" not in config:
            # Create stub repo for unavailable packages
            _stub_repo(
                name = "system_" + name,
                lib_name = name,
            )
            continue

        _system_lib_repo(
            name = "system_" + name,
            lib_name = name,
            path = config["path"],
            include_dirs = config.get("include_dirs", ["include"]),
            lib_dirs = config.get("lib_dirs", ["lib"]),
            libs = config.get("libs", [name]),
        )

system_deps = module_extension(
    implementation = _system_deps_impl,
)"#.to_string());

    lines.join("\n")
}

/// Detected pkg-config flags for a package.
#[derive(Debug, Clone, Default)]
pub struct PkgConfigFlags {
    /// Compiler flags (from --cflags)
    pub cflags: Vec<String>,
    /// Linker flags (from --libs)
    pub libs: Vec<String>,
}

/// Probe pkg-config to get actual flags for packages.
/// Returns None if pkg-config is not available or the package is not found.
pub fn probe_pkg_config(packages: &[String]) -> Option<PkgConfigFlags> {
    use std::process::Command;

    // Extract base package names (remove version constraints)
    let base_packages: Vec<&str> = packages
        .iter()
        .map(|p| p.split(">=").next().unwrap_or(p).trim())
        .collect();

    // Try to get cflags
    let cflags_output = Command::new("pkg-config")
        .args(["--cflags"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !cflags_output.status.success() {
        return None;
    }

    let cflags_str = String::from_utf8_lossy(&cflags_output.stdout);
    let cflags: Vec<String> = cflags_str
        .split_whitespace()
        .map(String::from)
        .collect();

    // Try to get libs
    let libs_output = Command::new("pkg-config")
        .args(["--libs"])
        .args(&base_packages)
        .output()
        .ok()?;

    if !libs_output.status.success() {
        return None;
    }

    let libs_str = String::from_utf8_lossy(&libs_output.stdout);
    let libs: Vec<String> = libs_str
        .split_whitespace()
        .map(String::from)
        .collect();

    Some(PkgConfigFlags { cflags, libs })
}

/// Generate linkopts for system libraries.
fn generate_system_linkopts(packages: &[String]) -> Vec<String> {
    let mut linkopts = Vec::new();

    for pkg in packages {
        let base = pkg.split(">=").next().unwrap_or(pkg).trim();

        match base {
            "glib-2.0" => linkopts.push("-lglib-2.0".to_string()),
            "gobject-2.0" => linkopts.push("-lgobject-2.0".to_string()),
            "gio-2.0" => linkopts.push("-lgio-2.0".to_string()),
            "gthread-2.0" => linkopts.push("-lgthread-2.0".to_string()),
            "gmodule-2.0" => linkopts.push("-lgmodule-2.0".to_string()),
            "libpeas-1.0" => linkopts.push("-lpeas-1.0".to_string()),
            "libdnf" => linkopts.push("-ldnf".to_string()),
            "smartcols" => linkopts.push("-lsmartcols".to_string()),
            "libcurl" | "curl" => linkopts.push("-lcurl".to_string()),
            "openssl" => {
                linkopts.push("-lssl".to_string());
                linkopts.push("-lcrypto".to_string());
            }
            "zlib" => linkopts.push("-lz".to_string()),
            "libxml-2.0" => linkopts.push("-lxml2".to_string()),
            _ => {
                let lib_name = base
                    .strip_prefix("lib")
                    .unwrap_or(base)
                    .split('-')
                    .next()
                    .unwrap_or(base);
                linkopts.push(format!("-l{lib_name}"));
            }
        }
    }

    linkopts
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_system_linkopts() {
        let packages = vec!["glib-2.0>=2.44.0".to_string()];
        let linkopts = generate_system_linkopts(&packages);
        assert_eq!(linkopts, vec!["-lglib-2.0"]);
    }

    #[test]
    fn test_deps_strategy_default() {
        let config = ThirdPartyConfig::default();
        assert_eq!(config.default_strategy, DepsStrategy::System);
    }
}
