load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "rebaze-cmake-file-api",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/rebaze-cmake",
        "@crates//:cmake-file-api",
        "@crates//:thiserror",
    ],
)

rust_test(
    name = "rebaze-cmake-file-api_test",
    crate = ":rebaze-cmake-file-api",
    edition = "2024",
)
