[package]
name = "rebaze-cmake-file-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CMake File API integration for rebaze"

[lints]
workspace = true

[dependencies]
cmake-file-api.workspace = true
rebaze-cmake.workspace = true
thiserror.workspace = true
