load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "rebaze-bzlmod",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:anyhow",
        "@crates//:async-channel",
        "@crates//:indexmap",
        "@crates//:once_cell",
        "@crates//:regex",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:url",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)

rust_test(
    name = "rebaze-bzlmod_test",
    crate = ":rebaze-bzlmod",
)
