[package]
name = "rebaze-bazel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Bazel file generator for rebaze"

[lints]
workspace = true

[dependencies]
rebaze-cmake.workspace = true
rebaze-gradle.workspace = true
rebaze-starlark.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
